/*
 * File: popcans/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('popcans.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    height: 58,
                    items: [
                        {
                            xtype: 'tbtext',
                            text: '6Cans后台管理系统'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    activeTab: 1,
                    items: [
                        {
                            xtype: 'panel',
                            title: '首页'
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            title: '作品审核',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    title: 'My Grid Panel',
                                                    store: 'PortfolioStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'owner',
                                                            text: '提交用户'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'title',
                                                            text: '作品名称'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            text: '提交时间'
                                                        }
                                                    ],
                                                    viewConfig: {

                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 2
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: '订单处理'
                        },
                        {
                            xtype: 'panel',
                            title: '属性调整'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});